apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hoge
  name: hoge
spec:
  containers:
  - image: ubuntu
    name: hoge
    command: ["sleep", "infinity"]
  nodeSelector:
    kubernetes.io/hostname: aks-nodepool-28795911-vmss000000
