resource_group_name = "rg-simpleakskubenet"
location = "japaneast"
ssh_public_key_name = "tsunomur"
ssh_public_key_resource_group = "NOTDELETE_rg-japaneast"
aks_version = "1.20.7"
aks_worker_admin_username = "tsunomur"
ssh_key_path = "~/.ssh/id_rsa.pub"
aks_worker_ssh_key_path = "~/.ssh/id_rsa.pub"
